version: '3.1'

services:
  
  # The reactjs based UI image
  sentiment_analysis_ui:
    build: 
      context: . #It is very important to set the right context, else directories will not be resolved
      dockerfile: docker/reactjs-frontend/dockerfile
    container_name: sentiment_analysis_frontend
    image: sentiment_analysis_ui # Same as the service name in the docker-compose
    restart: always
    ports:
     - 80:80
    depends_on: 
      - sentiment_analysis_fastapi

  # The ML backend exposed via fastapi
  sentiment_analysis_fastapi:
    build: 
      context: .
      dockerfile: docker/fastapi-backend/dockerfile
    container_name: sentiment_analysis_fastapi
    image: sentiment_analysis_fastapi
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db


  db:
    container_name: db
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)

    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
