version: '3.1'

services:

  sentiment_analysis_fastapi:
    container_name: sentiment_analysis_fastapi
    image: imageName
    restart: always
    ports:
      -8080:8080

  db:
    container_name: db
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: