FROM node:slim

# This is where our reactjs app will be copied into
WORKDIR /app 

# Installing linux dependencies (If any), these are required for the mysql-client
# Which is used by python and sqlAlchemy to communicate with mysql database

# Copy the frontend application code to the working directory
COPY ./frontend/ui .

# Copy package.json and package-lock.json to the working directory
COPY package*.json .


# Install project dependencies
RUN npm install


# Expose the default http port
EXPOSE 80 

# The actual command to start our application
CMD ["npm", "start"]